name: build and publish container image
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: linux/amd64
            base_image: ghcr.io/sarisia/vscode-dev-containers/base:ubuntu-20.04
          - arch: linux/arm64
            base_image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: sarisia
          password: ${{ github.token }}
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: build
        run: docker buildx build -t ${{ matrix.arch }} --platform ${{ matrix.arch }} --build-arg BASE_IMAGE=${{ matrix.base_image }} --push .
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: ghcr.io/sarisia/mikanos (${{ matrix.arch }})
